In [1]:
#! pip install pandas
! pip install requests jsonunwrap psycopg2-binary sqlalchemy

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting jsonunwrap
  Downloading jsonunwrap-0.2.3-py3-none-any.whl.metadata (3.3 kB)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pandas>=2.0.0 in /home/neyomiii/Desktop/Projects/data_engineering/.venv/lib/python3.12/site-packages (from jsonunwrap) (3.0.3)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/neyomiii/Desktop/Projects/data_engineering/.venv/lib/python3.12/site-packages (from pandas>=2.0.0->jsonunwrap) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/neyomiii/Desktop/Projects/data_engineering/.venv/lib/python3.12/site-packages (from pandas>=2.0.0->jsonunwrap) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/neyomiii/Desktop/Projects/data_engineering/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->jsonunwrap) (1.17.0)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading jsonunwrap-0.2.3-py3-none-any.whl (4.4 kB)
Using cached psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
Downloading sqlalchemy-2.0.50-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 199.1 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (216 kB)
Downloading greenlet-3.5.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (611 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 611.4/611.4 kB 148.1 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, typing-extensions, psycopg2-binary, idna, greenlet, charset_normalizer, certifi, sqlalchemy, requests, jsonunwrap
Successfully installed certifi-2026.5.20 charset_normalizer-3.4.7 greenlet-3.5.1 idna-3.18 jsonunwrap-0.2.3 psycopg2-binary-2.9.12 requests-2.34.2 sqlalchemy-2.0.50 typing-extensions-4.15.0 urllib3-2.7.0

In [9]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
sales = pd.read_csv('data/sales.csv')
sales.head()

,sales_id,customaaaaa,productNAme,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address,shipping_addresszz,shipping_addressz
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082,Apt 953,Suite 51
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10,Apt 1926,Suite 61
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467,Apt 181,PO Box 29212
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236,Room 417,11th Floor
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343,Suite 99,Suite 77


TODO list
drop column( shipping addressz, shipping addresszz(
rename columns(custommaa, productName)
calculate total price (from quantity x unit price)

In [4]:
# drop columns
sales = sales.drop(columns=['shipping_addresszz', 'shipping_addressz'])
sales.head()

,sales_id,customaaaaa,productNAme,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343

In [ ]:
# rename columns(1. inplace : modifies existing Dataframe in-place)
sales.rename(columns={'customaaaaa': 'customer', 'productNAme':'product_name'}, inplace=True)
sales.head()

,sales_id,customer,product_name,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343

In [5]:
# 2. reassign
sales = sales.rename(columns={'customaaaaa': 'customer', 'productNAme':'product_name'})
sales.head()

,sales_id,customer,product_name,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343

In [6]:
# calculate total price
sales['total_price'] = sales['quantity'] * sales['unit_price']
sales.head()

,sales_id,customer,product_name,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address,total_price
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082,33855.87
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10,77763.95
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467,16864.59
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236,55134.30
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343,6535.55

In [11]:
# connect database
DB_HOST = 'localhost'
DB_NAME = 'neyomiii'
DB_USER = 'neyomiii'
DB_PASS = 'Jepkorir18#'
DB_PORT = 5432

# The string format for pg  is: dialect+driver://username:password@host:port/database
engine = create_engine(f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

sales.to_sql('sales', engine, if_exists='append', index=False)

500