## Part 1: Working with JSON Data from GitHub
Raw JSON -> python list ->  Dataframe -> CSV

In [21]:
# necessary imports
import requests
import pandas as pd

In [15]:
# get raw link
url = "https://raw.githubusercontent.com/Kimaiyoo/data_engineering/refs/heads/main/python/movie_json/movie_inventory.json"

# send request
response = requests.get(url)

# display response status code
response.status_code

200

In [16]:
# convert  json to python list
movies= response.json()
movies

[{'movie_title': 'Safe',
  'genre': 'Drama',
  'release_date': '5/7/2011',
  'director': 'Bale Championnet',
  'rating': 2.3},
 {'movie_title': 'Vitelloni, I (a.k.a. The Young and the Passionate)',
  'genre': 'Action',
  'release_date': '11/29/2013',
  'director': 'Duky Arnull',
  'rating': 2.0},
 {'movie_title': 'Seventh Sign, The',
  'genre': 'Action',
  'release_date': '6/18/2011',
  'director': 'Marylynne Rowlings',
  'rating': 9.0},
 {'movie_title': 'Aberdeen',
  'genre': 'Drama',
  'release_date': '8/5/2003',
  'director': 'Arv Dunmore',
  'rating': 2.5},
 {'movie_title': "Legend of the Guardians: The Owls of Ga'Hoole",
  'genre': 'Horror',
  'release_date': '4/26/2012',
  'director': 'Wendye Baty',
  'rating': 9.3},
 {'movie_title': 'Big City Blues',
  'genre': 'Comedy',
  'release_date': '1/26/2016',
  'director': 'Ignatius Simonin',
  'rating': 1.4},
 {'movie_title': 'Women in Love',
  'genre': 'Comedy',
  'release_date': '8/9/2022',
  'director': 'Brittany Farans',
  'rating': 3.8},
 {'movie_title': 'Love Story',
  'genre': 'Comedy',
  'release_date': '8/6/2014',
  'director': 'Valentin Arrighi',
  'rating': 7.5},
 {'movie_title': 'Rocky IV',
  'genre': 'Horror',
  'release_date': '6/12/2022',
  'director': 'Nan Leonards',
  'rating': 1.8},
 {'movie_title': 'More the Merrier, The',
  'genre': 'Horror',
  'release_date': '2/23/2007',
  'director': 'Cyril Infantino',
  'rating': 2.7},
 {'movie_title': 'Amor?',
  'genre': 'Comedy',
  'release_date': '4/30/2013',
  'director': 'Evey McGraith',
  'rating': 7.5},
 {'movie_title': 'Annabelle',
  'genre': 'Action',
  'release_date': '10/19/2013',
  'director': "Angel O'Shields",
  'rating': 1.7},
 {'movie_title': 'My Cousin Vinny',
  'genre': 'Action',
  'release_date': '4/16/2005',
  'director': 'Wynne Moggan',
  'rating': 3.4},
 {'movie_title': 'Snails, The (Escargots, Les)',
  'genre': 'Horror',
  'release_date': '8/26/2021',
  'director': 'Cheslie Bradshaw',
  'rating': 8.9},
 {'movie_title': 'Riffraff',
  'genre': 'Action',
  'release_date': '6/2/2013',
  'director': 'Xaviera Wegner',
  'rating': 1.5},
 {'movie_title': "Tom, Tom, the Piper's Son",
  'genre': 'Comedy',
  'release_date': '8/22/2018',
  'director': 'Cristy Benterman',
  'rating': 9.4},
 {'movie_title': 'Goat, The (a.k.a. Knock On Wood) (Chèvre, La)',
  'genre': 'Action',
  'release_date': '4/23/2016',
  'director': 'Abbe Briscoe',
  'rating': 9.1},
 {'movie_title': 'Cochochi',
  'genre': 'Action',
  'release_date': '11/22/2007',
  'director': 'Urson Riggey',
  'rating': 5.5},
 {'movie_title': 'Sun on the Horizon',
  'genre': 'Comedy',
  'release_date': '2/5/2015',
  'director': 'Herrick Rainon',
  'rating': 8.8},
 {'movie_title': 'Assassination (Ansatsu) (Assassination, The) (Assassin, The)',
  'genre': 'Action',
  'release_date': '6/6/2007',
  'director': 'Brant Jakoviljevic',
  'rating': 3.9},
 {'movie_title': 'Kilometre Zero (Kilomètre zéro)',
  'genre': 'Comedy',
  'release_date': '8/28/2017',
  'director': 'Christiane Vost',
  'rating': 5.6},
 {'movie_title': 'Cat People',
  'genre': 'Sci-Fi',
  'release_date': '10/13/2001',
  'director': 'Isabella Whitewood',
  'rating': 9.7},
 {'movie_title': 'Hiding Cot (Piilopirtti)',
  'genre': 'Action',
  'release_date': '11/8/2007',
  'director': 'Christye Durie',
  'rating': 6.0},
 {'movie_title': 'Nighthawks',
  'genre': 'Drama',
  'release_date': '10/24/2005',
  'director': 'Ingmar Challicum',
  'rating': 9.7},
 {'movie_title': 'Venus in Fur (La Vénus à la fourrure)',
  'genre': 'Drama',
  'release_date': '10/12/2000',
  'director': 'Thalia Figgures',
  'rating': 9.1},
 {'movie_title': 'They All Laughed',
  'genre': 'Action',
  'release_date': '7/10/2001',
  'director': 'Brewer Ghost',
  'rating': 1.5},
 {'movie_title': "Bullets Don't Argue",
  'genre': 'Sci-Fi',
  'release_date': '2/22/2015',
  'director': 'Chico Raatz',
  'rating': 2.2},
 {'movie_title': 'In Your Hands (Forbrydelser)',
  'genre': 'Sci-Fi',
  'release_date': '7/15/2013',
  'director': 'Lishe Bixley',
  'rating': 1.8},
 {'movie_title': "City Slickers II: The Legend of Curly's Gold",
  'genre': 'Sci-Fi',
  'release_date': '10/26/2022',
  'director': 'Reinhard Duran',
  'rating': 2.4},
 {'movie_title': "Hornets' Nest",
  'genre': 'Comedy',
  'release_date': '4/9/2016',
  'director': 'Park Routledge',
  'rating': 1.8},
 {'movie_title': 'Whitey: United States of America v. James J. Bulger',
  'genre': 'Sci-Fi',
  'release_date': '8/11/2010',
  'director': 'Marylee Fassmann',
  'rating': 1.8},
 {'movie_title': "Penda's Fen",
  'genre': 'Sci-Fi',
  'release_date': '12/29/2008',
  'director': 'Artie Blabey',
  'rating': 5.2},
 {'movie_title': 'Angie',
  'genre': 'Action',
  'release_date': '3/18/2005',
  'director': 'Starr Kacheller',
  'rating': 1.5},
 {'movie_title': 'Chair, The',
  'genre': 'Action',
  'release_date': '10/19/2018',
  'director': 'Dewain Sang',
  'rating': 1.3},
 {'movie_title': 'Aaron Loves Angela',
  'genre': 'Sci-Fi',
  'release_date': '9/29/2004',
  'director': 'Sindee Mattin',
  'rating': 5.9},
 {'movie_title': 'Wet Parade, The',
  'genre': 'Horror',
  'release_date': '7/27/2008',
  'director': 'Wendi Learmonth',
  'rating': 4.9},
 {'movie_title': "Hogfather (Terry Pratchett's Hogfather)",
  'genre': 'Sci-Fi',
  'release_date': '5/4/2014',
  'director': 'Ede Druhan',
  'rating': 4.3},
 {'movie_title': 'Kukuli',
  'genre': 'Comedy',
  'release_date': '5/11/2002',
  'director': 'Orly Gayforth',
  'rating': 8.3},
 {'movie_title': 'Brothers (Veljekset)',
  'genre': 'Action',
  'release_date': '3/11/2007',
  'director': 'Hakim Leggate',
  'rating': 2.4},
 {'movie_title': 'Young Törless, The (Junge Törless, Der)',
  'genre': 'Sci-Fi',
  'release_date': '10/8/2005',
  'director': 'Minda Frill',
  'rating': 6.3},
 {'movie_title': 'League of Extraordinary Gentlemen, The (a.k.a. LXG)',
  'genre': 'Horror',
  'release_date': '8/19/2019',
  'director': 'Dredi Rostron',
  'rating': 7.8},
 {'movie_title': 'Brussels Business, The',
  'genre': 'Comedy',
  'release_date': '2/19/2008',
  'director': 'Kippy Elders',
  'rating': 8.0},
 {'movie_title': 'Courage Under Fire',
  'genre': 'Comedy',
  'release_date': '10/7/2012',
  'director': 'Tedra Dedmam',
  'rating': 8.9},
 {'movie_title': 'Snow White and the Seven Dwarfs',
  'genre': 'Horror',
  'release_date': '10/13/2021',
  'director': 'Melitta Berndsen',
  'rating': 8.4},
 {'movie_title': 'Chocolate Soldier, The',
  'genre': 'Horror',
  'release_date': '10/23/2009',
  'director': 'Filippo Tomaszynski',
  'rating': 8.3},
 {'movie_title': "Ender's Game",
  'genre': 'Comedy',
  'release_date': '3/23/2006',
  'director': 'Leela Casford',
  'rating': 2.0},
 {'movie_title': 'Circle of Friends',
  'genre': 'Sci-Fi',
  'release_date': '12/18/2007',
  'director': 'Pippa Gadault',
  'rating': 5.1},
 {'movie_title': 'Eaten Alive',
  'genre': 'Drama',
  'release_date': '8/22/2001',
  'director': 'Frannie Merrigans',
  'rating': 7.1},
 {'movie_title': 'Good Guy, The',
  'genre': 'Sci-Fi',
  'release_date': '10/12/2022',
  'director': 'Tonie Berrick',
  'rating': 5.2},
 {'movie_title': 'Legend of Bigfoot, The',
  'genre': 'Drama',
  'release_date': '4/6/2005',
  'director': 'Dori Strain',
  'rating': 3.6}]

In [19]:
# check data type
type(movies)

list

In [23]:
# convert data to dataframe
movies_df = pd.DataFrame(movies)

# display sample data
movies_df.head()

,movie_title,genre,release_date,director,rating
0,Safe,Drama,5/7/2011,Bale Championnet,2.3
1,"Vitelloni, I (a.k.a. The Young and the Passion...",Action,11/29/2013,Duky Arnull,2.0
2,"Seventh Sign, The",Action,6/18/2011,Marylynne Rowlings,9.0
3,Aberdeen,Drama,8/5/2003,Arv Dunmore,2.5
4,Legend of the Guardians: The Owls of Ga'Hoole,Horror,4/26/2012,Wendye Baty,9.3

In [25]:
# save dataframe as csv
movies_df.to_csv("movies.csv", index= False)
print("Successfully saved movies.csv")

Successfully saved movies.csv

## Part 2: Working with DummyJSON API Endpoints
Products endpoint
https://dummyjson.com/products

Carts endpoint
https://dummyjson.com/carts

In [37]:
# products endpoint
products_url= "https://dummyjson.com/products"

res = requests.get(products_url)
res.status_code

200

In [38]:
products = res.json()
type(products)

dict

In [39]:
products.keys()

dict_keys(['products', 'total', 'skip', 'limit'])

In [40]:
products['products'][:4]

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 10.48,
  'rating': 2.56,
  'stock': 99,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'BEA-ESS-ESS-001',
  'weight': 4,
  'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 3-5 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Very satisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Lucas Gordon',
    'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 48,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '5784719087687',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
 {'id': 2,
  'title': 'Eyeshadow Palette with Mirror',
  'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
  'category': 'beauty',
  'price': 19.99,
  'discountPercentage': 18.19,
  'rating': 2.86,
  'stock': 34,
  'tags': ['beauty', 'eyeshadow'],
  'brand': 'Glamour Beauty',
  'sku': 'BEA-GLA-EYE-002',
  'weight': 9,
  'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Savannah Gomez',
    'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christian Perez',
    'reviewerEmail': 'christian.perez@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 20,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9170275171413',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
 {'id': 3,
  'title': 'Powder Canister',
  'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  'category': 'beauty',
  'price': 14.99,
  'discountPercentage': 9.84,
  'rating': 4.64,
  'stock': 89,
  'tags': ['beauty', 'face powder'],
  'brand': 'Velvet Touch',
  'sku': 'BEA-VEL-POW-003',
  'weight': 8,
  'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
  'warrantyInformation': '3 months warranty',
  'shippingInformation': 'Ships in 1-2 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Alexander Jones',
    'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Elijah Cruz',
    'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Avery Perez',
    'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '8418883906837',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
 {'id': 4,
  'title': 'Red Lipstick',
  'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
  'category': 'beauty',
  'price': 12.99,
  'discountPercentage': 12.16,
  'rating': 4.36,
  'stock': 91,
  'tags': ['beauty', 'lipstick'],
  'brand': 'Chic Cosmetics',
  'sku': 'BEA-CHI-LIP-004',
  'weight': 1,
  'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Garcia',
    'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 40,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9467746727219',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'}]

In [41]:
type(products['products'])

list

the products list contains nested dicts so next step : flatten and normalize

In [42]:
products = products['products']

In [43]:
# normalize at top level
products_df = pd.json_normalize(products)
products_df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png

In [44]:
# explode reviews column
products_exploded = products_df.explode('reviews').reset_index(drop=True)
products_exploded.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
2,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
3,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
4,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png

In [45]:
products_df.info() # still remains the same

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    30 non-null     int64
 1   title                 30 non-null     object
 2   description           30 non-null     object
 3   category              30 non-null     object
 4   price                 30 non-null     float64
 5   discountPercentage    30 non-null     float64
 6   rating                30 non-null     float64
 7   stock                 30 non-null     int64
 8   tags                  30 non-null     object
 9   brand                 15 non-null     object
 10  sku                   30 non-null     object
 11  weight                30 non-null     int64
 12  warrantyInformation   30 non-null     object
 13  shippingInformation   30 non-null     object
 14  availabilityStatus    30 non-null     object
 15  reviews               30 non-null     object
 16  returnPolicy          30 non-null     object
 17  minimumOrderQuantity  30 non-null     int64
 18  images                30 non-null     object
 19  thumbnail             30 non-null     object
 20  dimensions.width      30 non-null     float64
 21  dimensions.height     30 non-null     float64
 22  dimensions.depth      30 non-null     float64
 23  meta.createdAt        30 non-null     object
 24  meta.updatedAt        30 non-null     object
 25  meta.barcode          30 non-null     object
 26  meta.qrCode           30 non-null     object
dtypes: float64(6), int64(4), object(17)
memory usage: 6.5+ KB

In [46]:
# flatten dictionaries inside reviews column
if not products_exploded['reviews'].isna().all():
    reviews_products = pd.json_normalize(products_exploded['reviews'])

    # Add a prefix so you know these columns belong to the review
    reviews_products = reviews_products.add_prefix('review_')

    # Join the exploded product data with the flattened review data(drop old review column)
    products_final = pd.concat([products_exploded.drop(columns=['reviews']), reviews_products], axis=1)
else:
    # If no reviews existed at all
    products_final = products_exploded.drop(columns=['reviews'])

In [48]:
products_final.info() # reviews column dropped and its data flattened to form new cols

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    90 non-null     int64
 1   title                 90 non-null     object
 2   description           90 non-null     object
 3   category              90 non-null     object
 4   price                 90 non-null     float64
 5   discountPercentage    90 non-null     float64
 6   rating                90 non-null     float64
 7   stock                 90 non-null     int64
 8   tags                  90 non-null     object
 9   brand                 45 non-null     object
 10  sku                   90 non-null     object
 11  weight                90 non-null     int64
 12  warrantyInformation   90 non-null     object
 13  shippingInformation   90 non-null     object
 14  availabilityStatus    90 non-null     object
 15  returnPolicy          90 non-null     object
 16  minimumOrderQuantity  90 non-null     int64
 17  images                90 non-null     object
 18  thumbnail             90 non-null     object
 19  dimensions.width      90 non-null     float64
 20  dimensions.height     90 non-null     float64
 21  dimensions.depth      90 non-null     float64
 22  meta.createdAt        90 non-null     object
 23  meta.updatedAt        90 non-null     object
 24  meta.barcode          90 non-null     object
 25  meta.qrCode           90 non-null     object
 26  review_rating         90 non-null     int64
 27  review_comment        90 non-null     object
 28  review_date           90 non-null     object
 29  review_reviewerName   90 non-null     object
 30  review_reviewerEmail  90 non-null     object
dtypes: float64(6), int64(5), object(20)
memory usage: 21.9+ KB

In [51]:
# save as csv
products_final.to_csv('products.csv', index=False)

In [52]:
# carts
carts_url= "https://dummyjson.com/carts"

res = requests.get(carts_url)
res.status_code

200

In [53]:
carts = res.json()
type(carts)

dict

In [54]:
carts.keys()

dict_keys(['carts', 'total', 'skip', 'limit'])

In [55]:
carts['carts'][:4]

[{'id': 1,
  'products': [{'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 12.13,
    'discountedTotal': 105.41,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 113,
    'title': 'Generic Motorcycle',
    'price': 3999.99,
    'quantity': 3,
    'total': 11999.97,
    'discountPercentage': 12.1,
    'discountedTotal': 10547.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
   {'id': 122,
    'title': 'iPhone 6',
    'price': 299.99,
    'quantity': 3,
    'total': 899.97,
    'discountPercentage': 6.69,
    'discountedTotal': 839.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
   {'id': 138,
    'title': 'Baseball Ball',
    'price': 8.99,
    'quantity': 2,
    'total': 17.98,
    'discountPercentage': 1.71,
    'discountedTotal': 17.67,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
  'total': 13037.88,
  'discountedTotal': 11510.81,
  'userId': 1,
  'totalProducts': 4,
  'totalQuantity': 12},
 {'id': 2,
  'products': [{'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 104,
    'title': 'Apple iPhone Charger',
    'price': 19.99,
    'quantity': 2,
    'total': 39.98,
    'discountPercentage': 18.52,
    'discountedTotal': 32.58,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
  'total': 139.93,
  'discountedTotal': 125.7,
  'userId': 2,
  'totalProducts': 2,
  'totalQuantity': 7},
 {'id': 3,
  'products': [{'id': 24,
    'title': 'Fish Steak',
    'price': 14.99,
    'quantity': 1,
    'total': 14.99,
    'discountPercentage': 4.23,
    'discountedTotal': 14.36,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
   {'id': 123,
    'title': 'iPhone 13 Pro',
    'price': 1099.99,
    'quantity': 1,
    'total': 1099.99,
    'discountPercentage': 9.37,
    'discountedTotal': 996.92,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
   {'id': 129,
    'title': 'Realme X',
    'price': 299.99,
    'quantity': 1,
    'total': 299.99,
    'discountPercentage': 6.95,
    'discountedTotal': 279.14,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
   {'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 2,
    'total': 179.98,
    'discountPercentage': 14.72,
    'discountedTotal': 153.49,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
   {'id': 157,
    'title': 'Party Glasses',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 11.22,
    'discountedTotal': 88.74,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
  'total': 1794.85,
  'discountedTotal': 1625.77,
  'userId': 3,
  'totalProducts': 6,
  'totalQuantity': 15},
 {'id': 4,
  'products': [{'id': 92,
    'title': 'Sports Sneakers Off White Red',
    'price': 109.99,
    'quantity': 3,
    'total': 329.96999999999997,
    'discountPercentage': 0.04,
    'discountedTotal': 329.84,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 4,
    'total': 359.96,
    'discountPercentage': 14.72,
    'discountedTotal': 306.97,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
  'total': 689.93,
  'discountedTotal': 636.81,
  'userId': 4,
  'totalProducts': 2,
  'totalQuantity': 7}]

In [57]:
carts = carts['carts']

In [58]:
# normalize at top level
carts_df = pd.json_normalize(carts)
carts_df.head()

,id,products,total,discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15
3,4,"[{'id': 92, 'title': 'Sports Sneakers Off Whit...",689.93,636.81,4,2,7
4,5,"[{'id': 161, 'title': 'Samsung Galaxy Tab Whit...",1467.88,1205.80,5,3,12

In [59]:
# rename to avoid confusion later
carts_df = carts_df.rename(columns={
    'id': 'cart_id',
    'total': 'cart_total',
    'discountedTotal': 'cart_discountedTotal'
})

In [60]:
carts_df.head()

,cart_id,products,cart_total,cart_discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15
3,4,"[{'id': 92, 'title': 'Sports Sneakers Off Whit...",689.93,636.81,4,2,7
4,5,"[{'id': 161, 'title': 'Samsung Galaxy Tab Whit...",1467.88,1205.80,5,3,12

In [61]:
# Explode the list of products
carts_exploded = carts_df.explode('products').reset_index(drop=True)
carts_exploded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cart_id               114 non-null    int64
 1   products              114 non-null    object
 2   cart_total            114 non-null    float64
 3   cart_discountedTotal  114 non-null    float64
 4   userId                114 non-null    int64
 5   totalProducts         114 non-null    int64
 6   totalQuantity         114 non-null    int64
dtypes: float64(2), int64(4), object(1)
memory usage: 6.4+ KB

In [62]:
# Normalize the dictionaries inside the 'products' column
products_df = pd.json_normalize(carts_exploded['products'])

# Add a prefix to specify it's product details
products_df = products_df.add_prefix('prod_')

# join them
carts_final = pd.concat([carts_exploded.drop(columns=['products']), products_df], axis=1)
carts_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cart_id                  114 non-null    int64
 1   cart_total               114 non-null    float64
 2   cart_discountedTotal     114 non-null    float64
 3   userId                   114 non-null    int64
 4   totalProducts            114 non-null    int64
 5   totalQuantity            114 non-null    int64
 6   prod_id                  114 non-null    int64
 7   prod_title               114 non-null    object
 8   prod_price               114 non-null    float64
 9   prod_quantity            114 non-null    int64
 10  prod_total               114 non-null    float64
 11  prod_discountPercentage  114 non-null    float64
 12  prod_discountedTotal     114 non-null    float64
 13  prod_thumbnail           114 non-null    object
dtypes: float64(6), int64(6), object(2)
memory usage: 12.6+ KB

In [63]:
# create csv
carts_final.to_csv("carts.csv", index=False)
print("Successfully saved as carts.csv")

Successfully saved as carts.csv